# Set new values in test registers
uint8 new_uint8
uint16 new_uint16
uint32 new_uint32
int8 new_int8
int16 new_int16
int32 new_int32
---
# Returns previous values + the fixed test value
uint32 fixed_val
uint8 prev_uint8
uint16 prev_uint16
uint32 prev_uint32
int8 prev_int8
int16 prev_int16
int32 prev_int32
